/************************************************************************************************************************************************
 * Project Euler (http://projecteuler.net) - Problem 2                                                                                          *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be: *
 *                                                                                                                                              *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...                                                                                                       *
 *                                                                                                                                              *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.           *
 ************************************************************************************************************************************************/

# include <stdlib.h>
# include <stdio.h>
# include <math.h>
void main()
{
	int i, j, k, c = 0;

	for (i = 1, j = 2; j < 4000000; )
	{
		if (j%2 == 0) c += j;
		k = j;
		j = i + j;
		i = k;
	}

	printf ("\n\n ----- %d ------ \n\n", c);
}
