/**********************************************************************************************************************************************************************************
 * Project Euler (http://projecteuler.net) - Problem 12                                                                                                                           *
 *                                                                                                                                                                                *
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be: *
 *                                                                                                                                                                                *
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...                                                                                                                                       *
 *                                                                                                                                                                                *
 * Let us list the factors of the first seven triangle numbers:                                                                                                                   *
 *                                                                                                                                                                                *
 *  1: 1                                                                                                                                                                          *
 *  3: 1,3                                                                                                                                                                        *
 *  6: 1,2,3,6                                                                                                                                                                    *
 * 10: 1,2,5,10                                                                                                                                                                   *
 * 15: 1,3,5,15                                                                                                                                                                   *
 * 21: 1,3,7,21                                                                                                                                                                   *
 * 28: 1,2,4,7,14,28                                                                                                                                                              *
 *                                                                                                                                                                                *
 * We can see that 28 is the first triangle number to have over five divisors.                                                                                                    *
 *                                                                                                                                                                                *
 * What is the value of the first triangle number to have over five hundred divisors?                                                                                             *
 **********************************************************************************************************************************************************************************/

# include <stdlib.h>
# include <stdio.h>
# include <math.h>
# include <time.h>
# define n 50

void main()
{
	int i, j, k, l, p[n], t;

	clock_t inicio, fim;

	inicio = clock ();

	/* find the first n prime numbers and store them in vector p */
	for (i = 2, j = 0; j < n; i++)
	{
		for (k = 0; k < j; k++)
			if (i % p[k] == 0) break;
		
		if (k == j) p[j++] = i;
	}

	for (i = 0; i < n; i++)
		printf (" %d,", p[i]);
/*
	for (i = 1, k = 1; i < n; i++) 
	{
*/		/* t is the triangular number.
		   it is the sum of an arithmetic progression 
		   that has 1 as first element and k as k-th 
		   element as well as common difference of 1 */
/*		t = (int) (0.5 * (1 + i) * i);

		printf ("\n %d = 1 ", t);

		for (i = 0, k = 1; p[i] <= (int) (0.5 * t) && pow (2, k) < n; i++)
		{
			while (t % p[i] == 0) 
			{
				k++;
				t /= p[i];
				printf ("* %d", t);
			}
		} 
	}

	printf ("\n - %d -\n", t);

	fim = clock();
	printf ("\n -- %f --\n", (double)(fim - inicio)/CLOCKS_PER_SEC); 
*/
}
